# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0005_userinfo_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.TextField(default='nothing', max_length=1024)),
                ('member_limit', models.IntegerField(default=200)),
                ('admin', models.ManyToManyField(related_name='group_admins', to='workflow.UserInfo')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.UserInfo')),
                ('members', models.ManyToManyField(related_name='group_members', to='workflow.UserInfo')),
            ],
        ),
    ]
