# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableControlFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_tp', models.CharField(choices=[('0', '\u9700\u6c42'), ('1', '\u4e34\u65f6\u914d\u5408')], max_length=2, verbose_name='\u4efb\u52a1\u7c7b\u578b')),
                ('req_no', models.CharField(max_length=20, verbose_name='\u9700\u6c42\u7f16\u53f7')),
                ('req_name', models.CharField(max_length=50, verbose_name='\u9700\u6c42\u540d\u79f0')),
                ('raise_user', models.CharField(max_length=10, verbose_name='\u9700\u6c42\u63d0\u51fa\u4eba')),
                ('accept_user', models.CharField(max_length=10, verbose_name='\u9700\u6c42\u53d7\u7406\u4eba')),
                ('accept_date', models.DateTimeField(verbose_name='\u9700\u6c42\u53d7\u7406\u65e5\u671f')),
                ('req_context', models.TextField(max_length=500, verbose_name='\u9700\u6c42\u5185\u5bb9')),
                ('req_sc_date', models.DateTimeField(verbose_name='\u9700\u6c42\u4e0a\u7ebf\u65f6\u95f4')),
                ('task_state', models.CharField(choices=[('0', '\u5f00\u53d1\u4e2d'), ('1', '\u5f00\u53d1\u7ed3\u675f'), ('2', '\u6253\u5305\u4e2d'), ('3', '\u6253\u5305\u7ed3\u675f')], max_length=2, verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('flow_state', models.CharField(choices=[('0', '\u8fdb\u884c\u4e2d'), ('1', '\u6253\u5305\u7ed3\u675f'), ('3', '\u5df2\u6295\u4ea7')], max_length=2, verbose_name='\u6d41\u7a0b\u72b6\u6001')),
                ('flow_end_user', models.CharField(blank=True, max_length=10, verbose_name='\u6d41\u7a0b\u7ed3\u675f\u4eba')),
                ('flow_end_date', models.DateTimeField(blank=True, verbose_name='\u6d41\u7a0b\u7ed3\u675f\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='TableSystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=30, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='TableWorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_item_crtdate', models.DateTimeField(auto_now=True, verbose_name='\u5de5\u4f5c\u9879\u521b\u5efa\u65f6\u95f4')),
                ('last_user', models.CharField(max_length=10, verbose_name='\u6307\u6d3e\u4eba')),
                ('curr_user', models.CharField(max_length=10, verbose_name='\u5904\u7406\u4eba')),
                ('work_item_context', models.TextField(verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
                ('plan_start_date', models.DateTimeField(verbose_name='\u8ba1\u5212\u5f00\u59cb\u65f6\u95f4')),
                ('plan_end_date', models.DateTimeField(verbose_name='\u8ba1\u5212\u7ed3\u675f\u65f6\u95f4')),
                ('act_start_date', models.DateTimeField(verbose_name='\u5b9e\u9645\u5f00\u59cb\u65f6\u95f4')),
                ('act_end_date', models.DateTimeField(verbose_name='\u5b9e\u9645\u7ed3\u675f\u65f6\u95f4')),
                ('work_item_state', models.CharField(choices=[('0', '\u5df2\u5b8c\u6210'), ('1', '\u8fdb\u884c\u4e2d'), ('2', '\u672a\u53d7\u7406')], max_length=2, verbose_name='\u5de5\u4f5c\u9879\u72b6\u6001')),
                ('work_item_enduser', models.CharField(max_length=10, verbose_name='\u5de5\u4f5c\u9879\u7ed3\u675f\u4eba')),
                ('flow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TableControlFlow')),
            ],
        ),
        migrations.AddField(
            model_name='tablecontrolflow',
            name='system_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TableSystemInfo', verbose_name='\u7cfb\u7edf\u540d\u79f0'),
        ),
    ]
