# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableworkitem',
            old_name='flow_id',
            new_name='flow',
        ),
    ]
