# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20160126_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecontrolflow',
            name='req_sc_date',
            field=models.DateTimeField(blank=True, verbose_name='\u9700\u6c42\u4e0a\u7ebf\u65f6\u95f4'),
        ),
    ]
